# Generated by Django 3.2.11 on 2022-02-05 21:51

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('students', '0005_auto_20220202_1559'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.group'),
        ),
        migrations.AlterField(
            model_name='student',
            name='age',
            field=models.IntegerField(default=20, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(120)]),
        ),
        migrations.AlterField(
            model_name='student',
            name='enroll_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
