# Generated by Django 3.2.11 on 2022-02-09 17:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_lecture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.EmailField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number',
            field=models.CharField(max_length=24, null=True, validators=[django.core.validators.RegexValidator('^(\\+\\d\\d?)?\\(\\d{3}\\)(\\d-?){7}$', message='Phone should be in format +1(111)222-33-44')]),
        ),
    ]
