# Generated by Django 3.2.11 on 2022-02-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_auto_20220209_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='lecture',
            name='level',
            field=models.PositiveIntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High')], default=1),
        ),
    ]
