# Generated by Django 3.2.11 on 2022-01-27 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0002_auto_20220127_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='linkedin_profile',
        ),
    ]
