# Generated by Django 3.2.11 on 2022-02-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0006_course'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='role',
            field=models.CharField(choices=[('M', 'Mentor'), ('T', 'Teacher')], default='T', max_length=1),
        ),
    ]
