# Generated by Django 3.2.11 on 2022-01-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('location', models.CharField(choices=[('O', 'Online'), ('KY', 'Kyiv'), ('KH', 'Kharkiv'), ('OD', 'Odesa'), ('DN', 'Dnipro')], max_length=20, null=True)),
                ('specialty', models.CharField(max_length=60)),
            ],
        ),
    ]
