# Generated by Django 3.2.11 on 2022-05-10 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_lecture_level'),
        ('groups', '0002_group_headman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='headman',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='headed_group', to='students.student'),
        ),
    ]
